### ISSUE TITLE
praeco helm chart install issue on AKS

### ISSUE THREAD

**Issue by redaER7** [daichi703n/praeco-helm#12]
Hello,

I am trying to install the praeco chart with a defaut installation running
```bash
helm upgrade -i praeco daichi703n/praeco \
  --namespace $NAMESPACE
```

`NAMESPACE` is my working namespace, I have the following error
```bash
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "praeco-elastalert-metrics" namespace: "prometheus" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first
```
I do not have a prometheus deployment , nor a prometheus namespace.

I am running it on a Azure AKS cluster , Kubernetes version v1.28.3

Any ideas why please ?

Thanks,

**Comment by daichi703n** [comment]
@redaER7 Hi,
Would you please set `elastalert.metrics.serviceMonitor.enabled` to `false` on your `vars.yml`?
This option disables creating ServiceMonitor resources.
https://github.com/daichi703n/elastalert-helm/blob/0.1.5/templates/serviceMonitor.yaml

Regards,

**Comment by redaER7** [comment]
works, thanks
installed with `values.yaml` now
```yaml
elastalert:
  metrics:
    serviceMonitor:
      enabled: false
```

**Comment by redaER7** [comment]
resolved
