### ISSUE TITLE
which version of elastalert is used?

### ISSUE THREAD

**Issue by StefanSa** [daichi703n/praeco-helm#3]
Hi,
Question, does your elastalert image correspond to the last version 0.2.4?

**Comment by daichi703n** [comment]
Hi, @StefanSa 
No, not yet updated. Sorry...
This ElastAlert is based on 0.2.1 and implemented some critical bugfix on my own.
https://github.com/daichi703n/elastalert-server/tree/fix/is_enabled

I'm planning to upgrade after checking bugfixes are implemented.

**Comment by nsano-rururu** [comment]
@daichi703n 

[yelp/elastalert](https://github.com/Yelp/elastalert)は、もうまともにメンテナンスされていません。
プルリクエストのマージは一切なく、メンテナーがissueの回答をすること自体が無くなってます。
今のところ、メンテナー交代は無さそうです。プルリクエストをレビューできる人が何人かいるようですが、
あまりレビューできていないようです。
ElastAlertを使い続けるなら[jertel/elastalert](https://github.com/jertel/elastalert)のaltブランチをベースに
@daichi703n さんの修正した内容を反映するほうがいいと思います。

https://github.com/jertel/elastalert
> Fork of yelp/elastalert
> The original yelp/elastalert repository has become mostly stale, with hundreds of open PRs and over 1000 open issues. The yelp team has acknowledged that they are winding down support of Elastalert. Consequently, it is difficult to merge fixes, dependency upgrades, and new features into Elastalert. Because of this, a fork of elastalert has been created. jertel/elastalert will be an alternate repository for updates, until a new maintainer is appointed by the Yelp team and it's clear that the new maintainers are responding to PRs and issues.
> 
> PRs are welcome, but must include tests, when possible. PRs will not be merged if they do not pass the automated CI workflows.

**Comment by daichi703n** [comment]
@nsano-rururu 状況共有ありがとうございます。
現状、主利用箇所では安定稼働しておりアップデート追従できていないのですが、今後のアップデート時は[jertel/elastalert](https://github.com/jertel/elastalert)の方を使うように確認・検討していこうと思います。

**Comment by nsano-rururu** [comment]
@daichi703n

[yelp/elastalert](https://github.com/Yelp/elastalert)ですが、現在のメンテナーが
issueに以下のコメントをしたので、別の人にメンテナーを引き継ぐことになりそうです。

>Hi, sorry for the lack of updates
>We have started the process of moving this to new owners. Still working on the details. I appreciate everyone's patience.

**google翻訳**

こんにちは、更新がないことをお詫びします

これを新しい所有者に移動するプロセスを開始しました。 まだ詳細に取り組んでいます。 皆様のご理解とご協力をよろしくお願いいたします。

**Comment by daichi703n** [comment]
@nsano-rururu 期待はしすぎず様子を見させていただこうと思います。共有ありがとうございます。

**Comment by nsano-rururu** [comment]
@daichi703n

jertel/elastalertですが、公式フォークにするようです。ElastAlertからElastAlert2に名前変えてます。
https://github.com/jertel/elastalert2

**Comment by daichi703n** [comment]
情報ありがとうございます。
フォーク先を見るようにしていきます。

**Comment by nsano-rururu** [comment]
@daichi703n

jertel/elastalert2のメンテナーになりました。急に以下のメールきました。
プルリクエストは出してましたけど、そんなに会話したことないんですけど。
![キャプチャ](https://user-images.githubusercontent.com/22293449/115997989-22ec2e00-a620-11eb-9929-0f374a7c857f.PNG)

**Comment by daichi703n** [comment]
@StefanSa 
I've fixed to use `praecoapp/elastalert-server` Docker Image which is based on ElastAlert2.
